---
- name: helloworld
  hosts: all
  tasks:
    - name: Quickcheck
      ping:
    - name: The os_family
      debug:
        msg: |
           The ansible_os_family: {{ ansible_os_family }}
           The ansible_distribution_major_version: {{ ansible_distribution_major_version }}
           The ansible_distribution_version: {{ ansible_distribution_version }}
