---
- name: helloworld
  hosts: all
  tasks:
    - name: ping module
      ping:
    - name: The os_family
      debug:
        msg: |
           The ansible_os_family: {{ ansible_os_family }}
           The ansible_distribution: {{ ansible_distribution }}
